import { College, Branch, Video, LiveEvent, Project } from "@/types";

export const seedColleges: College[] = [
  {
    id: "college-1",
    name: "Tech Innovation University",
    description: "A leading institution for technology and innovation, fostering the next generation of tech leaders.",
    location: "San Francisco, CA",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop",
    branches: ["branch-1", "branch-2", "branch-3"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "college-2",
    name: "Global Engineering Institute",
    description: "World-renowned engineering programs with state-of-the-art research facilities.",
    location: "Boston, MA",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop",
    branches: ["branch-4", "branch-5"],
    createdAt: new Date("2024-01-02"),
  },
  {
    id: "college-3",
    name: "Creative Arts Academy",
    description: "Where creativity meets technology. Specializing in digital arts and design.",
    location: "New York, NY",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop",
    branches: ["branch-6", "branch-7"],
    createdAt: new Date("2024-01-03"),
  },
];

export const seedBranches: Branch[] = [
  {
    id: "branch-1",
    name: "Computer Science",
    description: "Core programming, algorithms, data structures, and software engineering.",
    collegeId: "college-1",
    imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "branch-2",
    name: "Artificial Intelligence",
    description: "Machine learning, deep learning, and AI applications.",
    collegeId: "college-1",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "branch-3",
    name: "Cybersecurity",
    description: "Network security, ethical hacking, and digital forensics.",
    collegeId: "college-1",
    imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&auto=format&fit=crop",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "branch-4",
    name: "Mechanical Engineering",
    description: "Design, manufacturing, and robotics.",
    collegeId: "college-2",
    imageUrl: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop",
    createdAt: new Date("2024-01-02"),
  },
  {
    id: "branch-5",
    name: "Electrical Engineering",
    description: "Electronics, power systems, and embedded systems.",
    collegeId: "college-2",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop",
    createdAt: new Date("2024-01-02"),
  },
  {
    id: "branch-6",
    name: "Digital Design",
    description: "UI/UX design, graphic design, and visual communication.",
    collegeId: "college-3",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&auto=format&fit=crop",
    createdAt: new Date("2024-01-03"),
  },
  {
    id: "branch-7",
    name: "Game Development",
    description: "Game design, 3D modeling, and interactive media.",
    collegeId: "college-3",
    imageUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b2b0e?w=800&auto=format&fit=crop",
    createdAt: new Date("2024-01-03"),
  },
];

export const seedVideos: Video[] = [
  {
    id: "video-1",
    title: "Introduction to Python Programming",
    description: "Learn the basics of Python programming language for beginners.",
    url: "https://www.youtube.com/embed/kqtD5dpn9C8",
    branchId: "branch-1",
    uploaderId: "demo-user",
    uploaderName: "John Doe",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "video-2",
    title: "Data Structures Explained",
    description: "Understanding arrays, linked lists, trees, and graphs.",
    url: "https://www.youtube.com/embed/RBSGKlAvoiM",
    branchId: "branch-1",
    uploaderId: "demo-user",
    uploaderName: "Jane Smith",
    createdAt: new Date("2024-01-16"),
  },
  {
    id: "video-3",
    title: "Machine Learning Fundamentals",
    description: "Introduction to ML concepts and algorithms.",
    url: "https://www.youtube.com/embed/ukzFI9rgwfU",
    branchId: "branch-2",
    uploaderId: "demo-user",
    uploaderName: "Alex Johnson",
    createdAt: new Date("2024-01-17"),
  },
  {
    id: "video-4",
    title: "Neural Networks Deep Dive",
    description: "Understanding how neural networks work from scratch.",
    url: "https://www.youtube.com/embed/aircAruvnKk",
    branchId: "branch-2",
    uploaderId: "demo-user",
    uploaderName: "Emily Chen",
    createdAt: new Date("2024-01-18"),
  },
];

export const seedEvents: LiveEvent[] = [
  {
    id: "event-1",
    title: "Hackathon 2024",
    description: "Annual coding hackathon with prizes worth $10,000. Build innovative solutions in 48 hours!",
    date: new Date("2024-03-15T09:00:00"),
    link: "https://example.com/hackathon",
    branchId: "branch-1",
    uploaderId: "demo-user",
    uploaderName: "Tech Club",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "event-2",
    title: "AI Workshop Series",
    description: "Hands-on workshop on building AI applications using TensorFlow and PyTorch.",
    date: new Date("2024-02-20T14:00:00"),
    link: "https://example.com/ai-workshop",
    branchId: "branch-2",
    uploaderId: "demo-user",
    uploaderName: "AI Lab",
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "event-3",
    title: "Cybersecurity Conference",
    description: "Learn from industry experts about the latest in cybersecurity trends and threats.",
    date: new Date("2024-04-05T10:00:00"),
    branchId: "branch-3",
    uploaderId: "demo-user",
    uploaderName: "Security Team",
    createdAt: new Date("2024-01-14"),
  },
];

export const seedProjects: Project[] = [
  {
    id: "project-1",
    title: "Smart Campus App",
    description: "A mobile application for campus navigation, event tracking, and resource booking.",
    url: "https://github.com/example/smart-campus",
    branchId: "branch-1",
    contributorName: "Team Alpha",
    uploaderId: "demo-user",
    uploaderName: "Michael Brown",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "project-2",
    title: "AI Study Assistant",
    description: "An AI-powered chatbot that helps students with their coursework and assignments.",
    url: "https://github.com/example/ai-assistant",
    branchId: "branch-2",
    contributorName: "Team Beta",
    uploaderId: "demo-user",
    uploaderName: "Sarah Wilson",
    createdAt: new Date("2024-01-21"),
  },
  {
    id: "project-3",
    title: "Network Intrusion Detection",
    description: "Machine learning-based system for detecting network intrusions in real-time.",
    url: "https://github.com/example/intrusion-detection",
    branchId: "branch-3",
    contributorName: "Team Gamma",
    uploaderId: "demo-user",
    uploaderName: "David Lee",
    createdAt: new Date("2024-01-22"),
  },
  {
    id: "project-4",
    title: "Robotic Arm Controller",
    description: "Open-source robotic arm with precise movement control and IoT integration.",
    url: "https://github.com/example/robotic-arm",
    branchId: "branch-4",
    contributorName: "Robotics Club",
    uploaderId: "demo-user",
    uploaderName: "Lisa Chen",
    createdAt: new Date("2024-01-23"),
  },
];
